export const movieList = [
    'fast furious', 
    'harry potter', 
    'robin hood',
    'citizen kane',
    'ghost', 
    'highlander',
    'ponyo',
    'castle in the sky',
    'dragon ball z',
    'naruto',
    'spider man',
    'avatar',
    'batman',
    'El dorado',
    'the secret of Roan Inish',
    'the avengers',
    'tom and jerry',
    'dejavu',
    'k-pax',
    'pirates',
    'my fair lady',
    'titanic',
    'oliver twist',
    'the kid',
    'home',
    'hell boy',
    'bulletproof monk'
]